version: "3"

services:
  postgres:
    image: "postgres"
    container_name: "postgres"
    hostname: postgres
    restart: always
    env_file:
      ./.env
    expose:
      - 5432
    volumes:
      - postgres-data:/data/postgres
    ports:
      - 5432:5432
volumes:
  postgres-data:
